title: Design Guide 
description: Design guide for parts and features commonly used in MMC Designs
theme: just-the-docs

url: https://makersmakingchange.github.io/Open-AT-Design-Guide

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

#_includes/footer_custom.html
footer_content: 'Copyright (c) 2025 Neil Squire / Makers Making Change. This work is licensed under the [CC BY SA 4.0 License](http://creativecommons.org/licenses/by-sa/4.0)'